services:
  - type: web
    name: sexshopruropolis
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "cd 'sexy shop rur√≥polis' && gunicorn sexyshop.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: sexshop-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: sexshop-db
    region: oregon
    plan: free
    databaseName: sexshop
    user: sexshop
